### ISSUE TITLE
gsm calendarResources list empty result

### ISSUE THREAD

**Issue by RogerSik** [hanneshayashi/gsm#11]
When executing 
```
gsm calendarResources list
```
i get an empty result. 

But using 
```
gsm calendarLists list
```

I get a result.

API are granted to this credentials with this scopes
* https://www.googleapis.com/auth/calendar
* https://www.googleapis.com/auth/admin.directory.resource.calendar

Regarding to https://developers.google.com/admin-sdk/directory/reference/rest/v1/resources.calendars/list this should be enough. 

Edit1: and Hello Hannes, if you are reading this :D

**Comment by hanneshayashi** [comment]
Hi @RogerSik!
Can you please run
`gsm log clear`
`gsm calendarResources list`
`gsm log show`

**Comment by RogerSik** [comment]
The API scopes got changed. I changed this in Google Workspace Admin, but i forgot the set this in the configs new generation. 

```
gsm configs new \
  --name "example.org" --mode dwd \
  --subject xxx \
  --credentialsFile "gcp-credentials.json" \
  --scopes https://www.googleapis.com/auth/admin.directory.user.readonly,https://www.googleapis.com/auth/calendar,https://www.googleapis.com/auth/admin.directory.resource.calendar
```

after that it's now working. :)
