### ISSUE TITLE
Verify GSM.exe's workingness 

### ISSUE THREAD

**Issue by shann1976** [hanneshayashi/gsm#20]
Hello,

I am using Windows 11 and have installed go version : go1.21.6 windows/amd64, downloaded latest GSM build gsm-0.11.0_win-amd64 , configured it as :

> gsm.exe configs new --name domain_gsm_config --mode dwd --credentialsFile PATH-TO.json-File --subject my-gws-admin-account@domain.com
- created successfully

Loaded the config as 
> gsm.exe configs load --name domain_gsm_config
- loaded successfully

When I try to run the command : 
> gsm.exe drives list --useDomainAdminAccess
- I do not get any outputs or errors or anything, the command just returns back to command prompt

My questions are, how to check is gsm.exe is working properly and get the desired outputs of drives list

**Comment by hanneshayashi** [comment]
Hi @shann1976 !
Seeing no output usually means that GSM encountered an error. Errors get written to the log file. You can see the log file wiith `gsm log show`. See also https://gsm.hayashi-ke.online/gsm/log/show/ and https://gsm.hayashi-ke.online/#logging.

Let me know if this answers your question.

**Comment by shann1976** [comment]
I created a new project, service account & key within in. Authorized for domain_wide_delegation and run the config command as :
===
`.\gsm.exe configs new --name <name of your config> --mode dwd --credentialsFile <absolute path to your credentials.json> --subject actual-email-address`

`.\gsm.exe configs new --name <name of your config> --mode dwd --credentialsFile <absolute path to your credentials.json> --subject service-account-email-address`
===
Loading the config as :
===
`.\gsm.exe configs load --name itsupport-gsm-config`
===

The log shows in both cases 
====
```
 .\gsm.exe log show
2024/02/02 18:20:28 Unable to get client: Error parsing Service Account credential file to config: google: read JWT from JSON credentials: 'type' field is "" (expected "service_account")
2024/02/02 18:25:58 Unable to get client: Error parsing Service Account credential file to config: google: read JWT from JSON credentials: 'type' field is "" (expected "service_account")
2024/02/05 10:14:36 Unable to get client: Error parsing Service Account credential file to config: google: read JWT from JSON credentials: 'type' field is "" (expected "service_account")
```

How to resolve ?
===

**Comment by hanneshayashi** [comment]
The email address you specify with `--subject` needs to be the email address of the user you want to impersonate with Domain Wide Delegation (i.e. NOT the Service Account's email address).

The error message states that the Service Account Key is not in the correct format. Did you perhaps create an API Key instead by accident? Please see this guide from Google on how to create and download a Service Account Key: https://cloud.google.com/iam/docs/keys-create-delete#creating

GSM also supports Application Default Credentials, which do not require a Service Account Key: https://gsm.hayashi-ke.online/setup/#adc-application-default-credentials-mode

> If you want to use GSM on machine not in GCP, such as your local workstation, run gcloud auth application-default login and log in with a user account that can impersonate the Service Account you want to use for DWD.

> gsm configs new --name (name of your config) --mode adc --subject (email address of the user you want to impersonate) --serviceAccount (email address of the Service Account you want to impersonate)

**Comment by shann1976** [comment]
I have Google Workspace and I am an ADMIN on Google Workspace,  

1. enabled all the required API's including "IAM Service Account Credentials API"

2. Created a new Service Account and within that a new Key of JSON type. I am referring to this JSON file creating the required config

3. Enabled Service Account for Domain Wide Delegation for all the API's as detailed in https://gsm.hayashi-ke.online/setup/#scopes

4. https://console.cloud.google.com/apis/credentials?project=MY-PROJECT has only one "Service-Account" and within that "Service-Account" I have generated a key. I am using this JSON file while creating the config as detailed below 
The "Service-Account" has been enabled for Domain Wide Delegation as in #3

4. Created the config. file as : 
.\gsm.exe configs new --name my-gsm-config --mode dwd --credentialsFile Path-TO.json --subject myadmin@domain.com
====
Config file "myuser/.config/gsm/my-gsm-config.yaml" successfully created. Load with "gsm configs load --name my-gsm-config"
===

5. Loaded the config. file as 
.\gsm.exe configs load --name my-gsm-config
============
Rename .gsm.yaml to PATH/my-gsm-config.yaml
Rename myuser/.config/gsm/my-gsm-config.yaml to .gsm.yaml
'my-gsm-config' successfully loaded
============

6. .\gsm.exe log show
============
2024/02/02 18:20:28 Unable to get client: Error parsing Service Account credential file to config: google: read JWT from JSON credentials: 'type' field is "" (expected "service_account")
2024/02/02 18:25:58 Unable to get client: Error parsing Service Account credential file to config: google: read JWT from JSON credentials: 'type' field is "" (expected "service_account")
2024/02/05 10:14:36 Unable to get client: Error parsing Service Account credential file to config: google: read JWT from JSON credentials: 'type' field is "" (expected "service_account")
============

7. The JSON File downloaded & used is
===
{
  "type": "service_account",
  "project_id": "my-PROJECT",
  "private_key_id": "2386342899827439784279423790423749023",
  "private_key": "-----BEGIN PRIVATE KEY-----\abcde12344355476576576756756\n-----END PRIVATE KEY-----\n",
  "client_email": "svc-my-PROJECT@my-PROJECT.iam.gserviceaccount.com",
  "client_id": "1234567890999999",
  "auth_uri": "https://accounts.google.com/o/oauth2/auth",
  "token_uri": "https://oauth2.googleapis.com/token",
  "auth_provider_x509_cert_url": "https://www.googleapis.com/oauth2/v1/certs",
  "client_x509_cert_url": "https://www.googleapis.com/robot/v1/metadata/x509/svc-my-PROJECT%40my-PROJECT.iam.gserviceaccount.com",
  "universe_domain": "googleapis.com"
}
===

**Comment by hanneshayashi** [comment]
Thank you for the very detailed report!

I can't see anything wrong with your config and I just tried it on my machine and it worked without a hitch. Two questions though:
1. Did you specify the path to your JSON file as an absolute path or a relative path?
2. Did you edit the file in any way or save it in a different editor?

Is there any chance you could maybe try it with ADC? Service Account Keys are also a security risk and I recommend avoiding them whenever possible (that said, they are absolutely supported by GSM!)

**Comment by shann1976** [comment]
1. Absolute Path to the json file

2. No manual changes to downloaded json file or the config file generated
from gsm.exe

**Comment by hanneshayashi** [comment]
The only thing I can think of right now may be a bug related to Windows. I only use Linux or Mac and don't have a Windows box right now. I will have to spin up a VM in GCP to test it out but I know of people who use GSM on Windows without problems so this is really quite strange.

**Comment by hanneshayashi** [comment]
I just tested it in a fresh Windows 2022 Server VM on GCP with a new project and it worked fine (although I admit that GSM's handling for the first config could be a little nicer). Here are the commands that I ran:

1. Create a project
`gcloud projects create $PROJECT`
2. Enable Drive API (just this one for testing, enable anything you want / need)
`gcloud services enable drive.googleapis.com --project $PROJECT`
3. Create Service Account
`gcloud iam service-accounts create $SA_NAME`
4. Create Service Account Key
`gcloud iam service-accounts keys create creds.json --iam-account $SA_EMAIL`
5. Add Service Account's Client ID with the Drive Scope to DWD in Admin Console
6. Create new GSM config
`.\gsm configs new --name test --mode dwd --credentialsFile "C:\Users\myuser\Download\creds.json" --subject admin@example.com --scopes https://www.googleapis.com/auth/drive`
7. List files
`.\gsm files list --streamOutput`

**Comment by shann1976** [comment]
I renamed the downloaded JSON file to creds.json and created the configuration, run the example commands successfully.

I also imported the Powershell Module https://github.com/hanneshayashi/gsm-powershell and tried listing users as "List-GSMUsers" and that also worked, meaning all the below worked

I also took the sample script, after creating the folder named "exports" and ran it as :
./Export-Stuff.ps1 -ExportPath ./exports -Config myconfig -UserData -GroupData

However I get the below error:
`Error loading config: open C:\Users\myuser/.config/gsm/myconfig.yaml: The system cannot find the file specified`

Script did not terminate itself, and is still running > 2 hours without any error in STDOUT
Looks like it is generating the export user-wise and will take some time

Thanks for all the support 

I do have some other questions, will open another thread

**Comment by hanneshayashi** [comment]
Glad that you were able to resolve the issue.

You can ignore the error about loading the config file, since that config is already loaded.

The exports should be in an "exports" folder in the same folder where you ran the GSM executable.

I am going to close this issue since your original problem seems to be resolved now. If you experience any other issues, please feel free to open a new one.
